[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@openzeppelin/contracts=lib/openzeppelin-contracts/contracts", "@ethinfinitism/account-abstraction/contracts=lib/account-abstraction/contracts"]

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = {key = "${ETHERSCAN_API_KEY}"}

[rpc_endpoints]
mumbai = "${MUMBAI_RPC_URL}"







# See more config options https://github.com/foundry-rs/foundry/tree/master/config